name: portable-release-actions-workflow
on:
  workflow_dispatch:
permissions:
    contents: write    
    
jobs:
  build:
    name: Create Release
    runs-on: windows-latest
    env:
      targetZip: qemu-w64-portable-${{ github.ref_name }}.zip
    steps:
      - uses: actions/checkout@v4
      
      - name: installer
        shell: cmd
        run: |
          curl https://qemu.weilnetz.de/w64/qemu-w64-setup-20241220.exe -L -O
          dir
          
      - name: innoextract 
        shell: cmd
        run: |
          qemu-w64-setup-20241220.exe /S /D=%CD%\installation &&^
          cd installation &&^
          del qemu-uninstall.exe
      - name: Upload directory as artifact
        uses: actions/upload-artifact@v3
        with:
          name: qemu-w64-setup-20241220
          path: installation
